### PR TITLE
Find available python interpreters with bash first

### PR DESCRIPTION
**Pull request by yuema137**
The previous start_jupyter.py needs a pre-defined python interpreter to be executed. This needs to be done manually and could lead to bugs when the interpreter is unavailable. So I made it into a .sh file in which we:

-  First use bash to find the first available python interpreter from a given list.
-  Then use it to execute the following python codes.

The path of backup interpreters could be added to **potential_interpreters**

### CODE REVIEW

**Review by FaroutYLq — CHANGES_REQUESTED** [review]
Thanks @yuema137 . The idea sounds good to me. But I have two concerns:

- I would prefer replacing `/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/bin/python` with `/usr/bin/python3`, which is the default python3 interpreter on midway3 login nodes. The motivation is that, very often, cvmfs could be disconnected from midway3 login node due to the poor NFS mounting. If such fluctuation happens, we will not be able to even run notebook, which was not the case before this PR.
- Will we be ever running env_starter on other machines beyond midways? Currently this PR should work fine but we will have to add new interpreters. So, it might be nice to add some default interpreter to use, by `which python` and `which python3`, if the `potential_interpreters` is not found.

**Comment by yuema137** [comment]
Hi @FaroutYLq 
Thanks for the great suggestions. I made several changes according to them:

- Put the result of `which python` and `which python3` when they return an actual path (if it says no python then ignore them)
- Put the `cvfms` path in the end. So it will be the last one to be checked as we know it's usually unstable
- Separate the python script from the shell wrapper as what the wrapper does is only to find an available interpreter
- Print the potential_interepreter list, and the final used interpreter

An example output is like this:
```
[yuem@midway3-login4 env_starter]$ ./start_jupyter.sh --tag 2022.06.3 --ram 16000 --partition lgrandi
/usr/bin/python3
/dali/lgrandi/strax/miniconda3/envs/strax/bin/python
/cvmfs/xenon.opensciencegrid.org/releases/nT/development/anaconda/envs/XENONnT_development/bin/python
Using the interpreter: /usr/bin/python3
./start_jupyter.sh: line 60: /home/yuem/env_starter/first_bash_script_env.sh: No such file or directory

 __   __ ______  _   _   ____   _   _      _______ 
 \ \ / /|  ____|| \ | | / __ \ | \ | |    |__   __|
  \ V / | |__   |  \| || |  | ||  \| | _ __  | |   
   > <  |  __|  | . ` || |  | || . ` || '_ \ | |   
  / . \ | |____ | |\  || |__| || |\  || | | || |   
 /_/ \_\|______||_| \_| \____/ |_| \_||_| |_||_|   

                    The UChicago Analysis Center


Your HOME directory: /home/yuem
Submitting a new jupyter job
        Submitting sbatch /home/yuem/straxlab/notebook.sbatch
sbatch: Verify job submission ...
sbatch: Partition: lgrandi
sbatch: QOS-Flag: lgrandi
sbatch: Account: pi-lgrandi
sbatch: Verification: ***PASSED***
        sbatch returned: b'Submitted batch job 10580215\n'
        You have job id 10580215
Waiting for your job to start
        Looking for logfile /home/yuem/straxlab/notebook.log
        still waiting...
        still waiting...
Job started. Logfile is displayed below; we're looking for the jupyter URL.
        Starting jupyter job
        Using singularity image: /project2/lgrandi/xenonnt/singularity-images/xenonnt-2022.06.3.simg

            Copy/Paste this in your local terminal to ssh tunnel with remote
            -----------------------------------------------------------------
            ssh -N -f -L localhost:16814:10.50.252.48:16814 yuem@midway3.rcc.uchicago.edu
            -----------------------------------------------------------------

            Then open a browser on your local machine to the following address
            ------------------------------------------------------------------
            localhost:16814
            ------------------------------------------------------------------
            and use the token that appears below to login.

            OR replace  in the address below with localhost and copy
            to your local browser.

        [I 2023-11-16 19:12:35.477 ServerApp] jupyter_resource_usage | extension was successfully linked.
        [W 2023-11-16 19:12:35.492 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
        [W 2023-11-16 19:12:35.495 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
        [W 2023-11-16 19:12:35.501 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
        [I 2023-11-16 19:12:35.501 ServerApp] jupyterlab | extension was successfully linked.
        [W 2023-11-16 19:12:35.504 NotebookApp] Config option `kernel_spec_manager_class` not recognized by `NotebookApp`.
        [W 2023-11-16 19:12:35.507 NotebookApp] Config option `kernel_spec_manager_class` not recognized by `NotebookApp`.
        [W 2023-11-16 19:12:35.511 NotebookApp] Config option `kernel_spec_manager_class` not recognized by `NotebookApp`.
        [I 2023-11-16 19:12:35.512 ServerApp] nbclassic | extension was successfully linked.
        [I 2023-11-16 19:12:36.478 ServerApp] nb_conda | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
        [I 2023-11-16 19:12:36.480 ServerApp] nb_conda | extension was successfully linked.
        [I 2023-11-16 19:12:36.480 ServerApp] notebook_shim | extension was successfully linked.
        [I 2023-11-16 19:12:37.724 ServerApp] [nb_conda_kernels] enabled, 1 kernels found
        [I 2023-11-16 19:12:37.821 ServerApp] notebook_shim | extension was successfully loaded.
        [I 2023-11-16 19:12:37.822 ServerApp] jupyter_resource_usage | extension was successfully loaded.
        [I 2023-11-16 19:12:37.824 LabApp] JupyterLab extension loaded from /opt/XENONnT/anaconda/envs/XENONnT_2022.06.3/lib/python3.8/site-packages/jupyterlab
        [I 2023-11-16 19:12:37.824 LabApp] JupyterLab application directory is /opt/XENONnT/anaconda/envs/XENONnT_2022.06.3/share/jupyter/lab
        [I 2023-11-16 19:12:37.827 ServerApp] jupyterlab | extension was successfully loaded.
        [I 2023-11-16 19:12:37.828 ServerApp] [nb_conda] enabled
        [I 2023-11-16 19:12:37.828 ServerApp] nb_conda | extension was successfully loaded.
        [I 2023-11-16 19:12:37.834 ServerApp] nbclassic | extension was successfully loaded.
        [I 2023-11-16 19:12:37.835 ServerApp] Serving notebooks from local directory: /home/yuem
        [I 2023-11-16 19:12:37.835 ServerApp] Jupyter Server 1.18.0 is running at:
        [I 2023-11-16 19:12:37.835 ServerApp] http://10.50.252.48:16814/lab?token=31b85739853320112c8003990cc98bb7e3b6eb443fdef69a

Jupyter started succesfully
        Dumping URL http://10.50.252.48:16814/lab?token=31b85739853320112c8003990cc98bb7e3b6eb443fdef69a to cache file /home/yuem/.last_jupyter_url
        Parsing URL http://10.50.252.48:16814/lab?token=31b85739853320112c8003990cc98bb7e3b6eb443fdef69a

All done! If you have linux, execute this command on your laptop:

ssh -fN -L 16814:10.50.252.48:16814 yuem@dali-login2.rcc.uchicago.edu && sensible-browser http://localhost:16814/?token=31b85739853320112c8003990cc98bb7e3b6eb443fdef69a

If you have a mac, instead do:

ssh -fN -L 16814:10.50.252.48:16814 yuem@dali-login2.rcc.uchicago.edu && open "http://localhost:16814/?token=31b85739853320112c8003990cc98bb7e3b6eb443fdef69a"

Happy strax analysis, yuem!
```

**Review by FaroutYLq — APPROVED** [review]
Looks good to me now. Thanks. I was a bit lazy to test but I trust you.

**Comment by yuema137** [comment]
@FaroutYLq Thanks! I will keep an eye on this package in case there's any issue.

**Pull request merged**
