### PR TITLE
Add memory limit for notebooks in reservation queue

### PR DESCRIPTION
**Pull request by WenzDaniel**
Limits total memory for notebooks in reservation queue to be 16 GB. See also [slack chat](https://xenonnt.slack.com/archives/C016DM0JPK9/p1643959219935399)

### CODE REVIEW

**Comment by JoranAngevaare** [comment]
@WenzDaniel , absolutely agree. I'd have two suggestions if you agree:
 - Hardcode the limit, I think people will ignore print statements. If they want more memory, use another queue, no exceptions.
 - Check that one is actually not specifying the partition already because if one specifies `--partition dali` you shouldn't also have to specify `--bypass_reservation`

**Comment by WenzDaniel** [comment]
Sure, can do. Not entirely sure what you mean in point 1 though. 

> Hardcode the limit, I think people will ignore print statements. If they want more memory, use another queue, no exceptions.

So you mean explicitly terminating the job instead of bypassing the reservation queue?

**Comment by JoranAngevaare** [comment]
whoop sorry, you are right, you already hardcoded it, I retract my first suggestion 😉

**Comment by WenzDaniel** [comment]
Okay your second comment should be addressed now.

**Comment by JoranAngevaare** [comment]
nice

**Review by JoranAngevaare — APPROVED** [review]

**Comment by JoranAngevaare** [comment]
quickly tested it, seems to work, so I'll merge

**Pull request merged**
